# Generated by Django 5.0.1 on 2024-09-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
